name: postgres-ai
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres-ai:v1
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data-postgres-ai
      - ./activate-extension.sql:/docker-entrypoint-initdb.d/0-activate-extension.sql
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectordb
